# Generated by Django 2.2.1 on 2020-02-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='img',
            field=models.ImageField(default='img', upload_to='img/'),
        ),
    ]
