# Generated by Django 2.2.1 on 2020-02-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200206_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='sub',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
