# Generated by Django 2.2.1 on 2020-02-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_prop_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop_cal',
            name='sub',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
