# Generated by Django 2.2.1 on 2020-02-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_prop_cal_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prop',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='prop_cal',
            name='sub',
        ),
    ]
