# Generated by Django 2.2.1 on 2020-02-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200227_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='sub',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prop_cal',
            name='sub',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
