# Generated by Django 2.2.1 on 2020-04-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_prop_liner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='sub',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prop',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prop_cal',
            name='sub',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prop_cal',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prop_liner',
            name='sub',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prop_liner',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
