# Generated by Django 2.2.1 on 2020-04-04 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20200404_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prop',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='prop_cal',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='prop_liner',
            name='sub',
        ),
    ]
