# Generated by Django 2.2.1 on 2020-04-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20200404_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='tit',
            field=models.CharField(default='title', max_length=200),
        ),
        migrations.AddField(
            model_name='prop_cal',
            name='tit',
            field=models.CharField(default='title', max_length=200),
        ),
        migrations.AddField(
            model_name='prop_liner',
            name='tit',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
