# Generated by Django 2.2.1 on 2020-04-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20200404_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prop_cal',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prop_liner',
            name='title',
            field=models.TextField(),
        ),
    ]
