# Generated by Django 2.2.1 on 2020-04-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_prop_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prop_text',
            new_name='Prop_mine',
        ),
    ]
