# Generated by Django 2.2.1 on 2020-04-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20200407_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='head',
            field=models.TextField(default='def'),
        ),
        migrations.AddField(
            model_name='prop_cal',
            name='head',
            field=models.TextField(default='def'),
        ),
        migrations.AddField(
            model_name='prop_liner',
            name='head',
            field=models.TextField(default='def'),
        ),
        migrations.AddField(
            model_name='prop_mine',
            name='head',
            field=models.TextField(default='def'),
        ),
    ]
