# Generated by Django 2.2.1 on 2020-04-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20200411_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prop',
            name='title',
        ),
        migrations.RemoveField(
            model_name='prop_cal',
            name='title',
        ),
        migrations.RemoveField(
            model_name='prop_liner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='prop_mine',
            name='title',
        ),
    ]
